#!/bin/sh
# Applications
pgrep conky || conky &
pidof redshift || redshift &
xrdb ~/.Xresources
firefox &
mailsync &

mpd-mpris &
pgrep bspswallow || ~/.local/scripts/bspwm/bspswallow &

xautolock -detectsleep -time 10 -locker lock.sh -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &

mate-power-manager &
