#!/bin/bash
fname=`ncmpcpp --quiet --current-song "%f"`
file=`find /data/Music -name "$fname"`

ffmpeg -i "$file" -loglevel quiet  -an -vcodec copy -y /tmp/cover.jpg
if [ -e /tmp/cover.jpg ]
then
	notify-send -i /tmp/cover.jpg "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)"
	rm /tmp/cover.jpg
else
	notify-send -i ~/player_icon.png "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)"
fi
